// lib/benz-provinces.ts — จังหวัดไทยครบ 77 สำหรับ directory "อู่เบนซ์ทั่วไทย"
// slug ↔ ชื่อไทย ↔ อังกฤษ · garages.province เก็บเป็น "ชื่อไทย" (th)
// อัปเดต 26 ก.ค. 2026: ขยายจาก 10 → 77 จังหวัด (รองรับอู่ทุกจังหวัด + backfill)

export type Province = { slug: string; th: string; en: string }

export const PROVINCES: Province[] = [
  { slug: 'bangkok', th: 'กรุงเทพมหานคร', en: 'Bangkok' },
  { slug: 'samut-prakan', th: 'สมุทรปราการ', en: 'Samut Prakan' },
  { slug: 'nonthaburi', th: 'นนทบุรี', en: 'Nonthaburi' },
  { slug: 'pathum-thani', th: 'ปทุมธานี', en: 'Pathum Thani' },
  { slug: 'phra-nakhon-si-ayutthaya', th: 'พระนครศรีอยุธยา', en: 'Phra Nakhon Si Ayutthaya' },
  { slug: 'ang-thong', th: 'อ่างทอง', en: 'Ang Thong' },
  { slug: 'lopburi', th: 'ลพบุรี', en: 'Lopburi' },
  { slug: 'sing-buri', th: 'สิงห์บุรี', en: 'Sing Buri' },
  { slug: 'chai-nat', th: 'ชัยนาท', en: 'Chai Nat' },
  { slug: 'saraburi', th: 'สระบุรี', en: 'Saraburi' },
  { slug: 'nakhon-nayok', th: 'นครนายก', en: 'Nakhon Nayok' },
  { slug: 'nakhon-pathom', th: 'นครปฐม', en: 'Nakhon Pathom' },
  { slug: 'samut-sakhon', th: 'สมุทรสาคร', en: 'Samut Sakhon' },
  { slug: 'samut-songkhram', th: 'สมุทรสงคราม', en: 'Samut Songkhram' },
  { slug: 'suphan-buri', th: 'สุพรรณบุรี', en: 'Suphan Buri' },
  { slug: 'kanchanaburi', th: 'กาญจนบุรี', en: 'Kanchanaburi' },
  { slug: 'ratchaburi', th: 'ราชบุรี', en: 'Ratchaburi' },
  { slug: 'phetchaburi', th: 'เพชรบุรี', en: 'Phetchaburi' },
  { slug: 'prachuap-khiri-khan', th: 'ประจวบคีรีขันธ์', en: 'Prachuap Khiri Khan' },
  { slug: 'chonburi', th: 'ชลบุรี', en: 'Chonburi' },
  { slug: 'rayong', th: 'ระยอง', en: 'Rayong' },
  { slug: 'chanthaburi', th: 'จันทบุรี', en: 'Chanthaburi' },
  { slug: 'trat', th: 'ตราด', en: 'Trat' },
  { slug: 'chachoengsao', th: 'ฉะเชิงเทรา', en: 'Chachoengsao' },
  { slug: 'prachinburi', th: 'ปราจีนบุรี', en: 'Prachinburi' },
  { slug: 'sa-kaeo', th: 'สระแก้ว', en: 'Sa Kaeo' },
  { slug: 'chiang-mai', th: 'เชียงใหม่', en: 'Chiang Mai' },
  { slug: 'chiang-rai', th: 'เชียงราย', en: 'Chiang Rai' },
  { slug: 'lamphun', th: 'ลำพูน', en: 'Lamphun' },
  { slug: 'lampang', th: 'ลำปาง', en: 'Lampang' },
  { slug: 'uttaradit', th: 'อุตรดิตถ์', en: 'Uttaradit' },
  { slug: 'phrae', th: 'แพร่', en: 'Phrae' },
  { slug: 'nan', th: 'น่าน', en: 'Nan' },
  { slug: 'phayao', th: 'พะเยา', en: 'Phayao' },
  { slug: 'mae-hong-son', th: 'แม่ฮ่องสอน', en: 'Mae Hong Son' },
  { slug: 'nakhon-sawan', th: 'นครสวรรค์', en: 'Nakhon Sawan' },
  { slug: 'uthai-thani', th: 'อุทัยธานี', en: 'Uthai Thani' },
  { slug: 'kamphaeng-phet', th: 'กำแพงเพชร', en: 'Kamphaeng Phet' },
  { slug: 'tak', th: 'ตาก', en: 'Tak' },
  { slug: 'sukhothai', th: 'สุโขทัย', en: 'Sukhothai' },
  { slug: 'phitsanulok', th: 'พิษณุโลก', en: 'Phitsanulok' },
  { slug: 'phichit', th: 'พิจิตร', en: 'Phichit' },
  { slug: 'phetchabun', th: 'เพชรบูรณ์', en: 'Phetchabun' },
  { slug: 'nakhon-ratchasima', th: 'นครราชสีมา', en: 'Nakhon Ratchasima' },
  { slug: 'buriram', th: 'บุรีรัมย์', en: 'Buriram' },
  { slug: 'surin', th: 'สุรินทร์', en: 'Surin' },
  { slug: 'sisaket', th: 'ศรีสะเกษ', en: 'Sisaket' },
  { slug: 'ubon-ratchathani', th: 'อุบลราชธานี', en: 'Ubon Ratchathani' },
  { slug: 'yasothon', th: 'ยโสธร', en: 'Yasothon' },
  { slug: 'chaiyaphum', th: 'ชัยภูมิ', en: 'Chaiyaphum' },
  { slug: 'amnat-charoen', th: 'อำนาจเจริญ', en: 'Amnat Charoen' },
  { slug: 'nong-bua-lamphu', th: 'หนองบัวลำภู', en: 'Nong Bua Lamphu' },
  { slug: 'khon-kaen', th: 'ขอนแก่น', en: 'Khon Kaen' },
  { slug: 'udon-thani', th: 'อุดรธานี', en: 'Udon Thani' },
  { slug: 'loei', th: 'เลย', en: 'Loei' },
  { slug: 'nong-khai', th: 'หนองคาย', en: 'Nong Khai' },
  { slug: 'maha-sarakham', th: 'มหาสารคาม', en: 'Maha Sarakham' },
  { slug: 'roi-et', th: 'ร้อยเอ็ด', en: 'Roi Et' },
  { slug: 'kalasin', th: 'กาฬสินธุ์', en: 'Kalasin' },
  { slug: 'sakon-nakhon', th: 'สกลนคร', en: 'Sakon Nakhon' },
  { slug: 'nakhon-phanom', th: 'นครพนม', en: 'Nakhon Phanom' },
  { slug: 'mukdahan', th: 'มุกดาหาร', en: 'Mukdahan' },
  { slug: 'bueng-kan', th: 'บึงกาฬ', en: 'Bueng Kan' },
  { slug: 'nakhon-si-thammarat', th: 'นครศรีธรรมราช', en: 'Nakhon Si Thammarat' },
  { slug: 'krabi', th: 'กระบี่', en: 'Krabi' },
  { slug: 'phang-nga', th: 'พังงา', en: 'Phang Nga' },
  { slug: 'phuket', th: 'ภูเก็ต', en: 'Phuket' },
  { slug: 'surat-thani', th: 'สุราษฎร์ธานี', en: 'Surat Thani' },
  { slug: 'ranong', th: 'ระนอง', en: 'Ranong' },
  { slug: 'chumphon', th: 'ชุมพร', en: 'Chumphon' },
  { slug: 'songkhla', th: 'สงขลา', en: 'Songkhla' },
  { slug: 'satun', th: 'สตูล', en: 'Satun' },
  { slug: 'trang', th: 'ตรัง', en: 'Trang' },
  { slug: 'phatthalung', th: 'พัทลุง', en: 'Phatthalung' },
  { slug: 'pattani', th: 'ปัตตานี', en: 'Pattani' },
  { slug: 'yala', th: 'ยะลา', en: 'Yala' },
  { slug: 'narathiwat', th: 'นราธิวาส', en: 'Narathiwat' },
]

export const provinceBySlug = (slug: string): Province | undefined =>
  PROVINCES.find((p) => p.slug === slug) ||
  PROVINCES.find((p) => p.th === decodeURIComponent(slug))

export const provinceSlug = (th: string): string =>
  PROVINCES.find((p) => p.th === th)?.slug || encodeURIComponent(th)
